version: '3.1'

services:

  db:
    image: mysql:5.6
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: sbc
      MYSQL_USER: dev
      MYSQL_PASSWORD: 123456
    volumes:
      - "/var/mysql/data/db:/var/lib/mysql"
      - "./my.cnf:/etc/mysql/my.cnf"
    ports:
      - "3306:3306"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8282:8080